rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby
  - rbx
branches:
  only:
    - master
notifications:
  recipients:
    - ttilley@gmail.com
    - wycats@gmail.com
    - thibaud@thibaud.me
    - rymai@rymai.me
    - michi@netzpiraten.ch
