rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
bundler_args: --without=development
branches:
  only:
    - master
notifications:
  recipients:
    - ttilley@gmail.com
    - wycats@gmail.com
    - thibaud@thibaud.me
    - rymai@rymai.me
    - michi@netzpiraten.ch
